### ISSUE TITLE
Dæmi 1 virkar ekki - corse villa

### ISSUE THREAD

**Issue by bippi** [cadia-lvl/WebRICE#60]
keyrt í dev umhverfi - npm run dev
http://localhost:3000/maltaekni.html
smellt á "spila hnapp"

cors villa

![image](https://user-images.githubusercontent.com/1389575/132207630-14b5cac2-0cf2-446d-9c5c-3d807703257e.png)

**Comment by rkjaran** [comment]
Smá vandamál á tts.tiro.is. Ætti að vera komið í lag.

**Comment by SmariF89** [comment]
Virðist allt virka núna. Takk fyrir ábendinguna.
